### ISSUE TITLE
from tastyworks.streamer import DataStreamer not working

### ISSUE THREAD

**Issue by xiaxio** [Graeme22/tastyworks-api#1]
Hi
I just installed the API, but it gives me the error ModuleNotFoundError: No module named 'aiocometd' when running from tastyworks.streamer import DataStreamer
Any ideas on how to solve this?
I am using Windows 11, Python 3.8 and PyCharm 2021.2.1 Community Edition
Thanks!

**Comment by Graeme22** [comment]
Sorry for not getting back to you until now! Quick solution is `pip install aiocometd`, however I may need to edit the project requirements and setup.py to make sure that's included in the future.

**Comment by Graeme22** [comment]
This is fixed in the latest release `4.2.0`.

**Comment by xiaxio** [comment]
Thanks! I will check it!
